// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVRPno1vgZa3MQH9ww2iGRpbIebVImick',
    appId: '1:1023616041877:web:7a492c28cf646ac693ac9c',
    messagingSenderId: '1023616041877',
    projectId: 'itc-meet2-178e9',
    authDomain: 'itc-meet2-178e9.firebaseapp.com',
    databaseURL: 'https://itc-meet2-178e9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'itc-meet2-178e9.firebasestorage.app',
    measurementId: 'G-BH53J0TEKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO5dIwpGVaQSvNJStu0l53FMMZcvrna6Y',
    appId: '1:1023616041877:android:416e44ff5eafc93393ac9c',
    messagingSenderId: '1023616041877',
    projectId: 'itc-meet2-178e9',
    databaseURL: 'https://itc-meet2-178e9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'itc-meet2-178e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCipdoOhLGi-OaUlYGBSK8myV0l4vo6kw8',
    appId: '1:1023616041877:ios:74102f848c4b0d0293ac9c',
    messagingSenderId: '1023616041877',
    projectId: 'itc-meet2-178e9',
    databaseURL: 'https://itc-meet2-178e9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'itc-meet2-178e9.firebasestorage.app',
    iosBundleId: 'com.example.itcPert2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCipdoOhLGi-OaUlYGBSK8myV0l4vo6kw8',
    appId: '1:1023616041877:ios:74102f848c4b0d0293ac9c',
    messagingSenderId: '1023616041877',
    projectId: 'itc-meet2-178e9',
    databaseURL: 'https://itc-meet2-178e9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'itc-meet2-178e9.firebasestorage.app',
    iosBundleId: 'com.example.itcPert2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVRPno1vgZa3MQH9ww2iGRpbIebVImick',
    appId: '1:1023616041877:web:0eab397a9c256e9e93ac9c',
    messagingSenderId: '1023616041877',
    projectId: 'itc-meet2-178e9',
    authDomain: 'itc-meet2-178e9.firebaseapp.com',
    databaseURL: 'https://itc-meet2-178e9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'itc-meet2-178e9.firebasestorage.app',
    measurementId: 'G-ESVTRK51DS',
  );
}
